version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum  ".circleci/config.yml" }}

      - run:
          name: update sdk & accept licenses
          command: sdkmanager --update && echo "yes" | sdkmanager --licenses

      - run:
          name: Setup emulator
          command: sdkmanager "system-images;android-25;google_apis;x86" && echo "no" | avdmanager create avd -n avd_25_x86 -k "system-images;android-25;google_apis;x86"

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd avd_25_x86 -noaudio -no-boot-anim -no-window -accel on
          background: true

      - save_cache:
          paths:
            - ~/.gradle
            - ~/.android/
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum  ".circleci/config.yml" }}

      - run:
          name: Run Esspresso Tests
          command: ./gradlew connectedAndroidTest

#      - run:
#          name: Build Debug apk
#          command: ./gradlew clean assembleDebug
#      # upload apk to github
#      - deploy:
#          command: ./apkrelease.sh
#      - store_artifacts:
##      pick artifact from
#          path: app/build/outputs/apk
#          destination: apkFolder
#      optional extra path
#          destination: buildApk
#      - store_test_results:
#          path: app/build/test-results
