version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout

      - restore_cache:
#          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum  "setup_emulator.sh" }}
          key: "two"

      - run:
          name: Setup emulator
          command: sdkmanager "system-images;android-22;default;armeabi-v7a" && echo "no" | avdmanager create avd --force -n test -k "system-images;android-22;default;armeabi-v7a"

      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on
          background: true

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          paths:
            - ~/.gradle
            - ~/.android
          key: "two"

      - run:
          name: Run Esspresso Tests
          command: ./gradlew connectedAndroidTest

#      - run:
#          name: Build Debug apk
#          command: ./gradlew clean assembleDebug
#      # upload apk to github
#      - deploy:
#          command: ./apkrelease.sh
#      - store_artifacts:
##      pick artifact from
#          path: app/build/outputs/apk
#          destination: apkFolder
#      optional extra path
#          destination: buildApk
#      - store_test_results:
#          path: app/build/test-results
