version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
      APK_DIR: apk_dir
      GIT_TAG: `git describe --abbrev=0 --tags`
      APK_LOCATION: "app/build/outputs/apk/"
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Build Debug apk
          command: ./gradlew clean assembleDebug
          name: Upload Artifacts to Github Release
          command: ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME $CIRCLE_TAG-$CIRCLE_SHA1 $APK_LOCATION || true


      - store_artifacts:
#      pick artifact from
          path: app/build/outputs/apk
#      optional extra path
          destination: $APK_DIR
      - store_test_results:
          path: app/build/test-results