version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout

      - restore_cache:
         key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: Setup emulator
          command: sdkmanager "system-images;android-22;default;armeabi-v7a" && echo "no" | avdmanager create avd --force -n avd_22_arm -k "system-images;android-22;default;armeabi-v7a"

      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd avd_22_arm -noaudio -no-boot-anim
#          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd avd_22_arm -noaudio -no-boot-anim -no-window -accel on
          background: true

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies --stacktrace

      - save_cache:
          paths:
            - ~/.gradle
            - ~/.android
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: Wait for Emulator
          command: ./wait_for_emulator.sh

      - run:
          name: Run Esspresso test
          command: ./gradlew installDebug connectedAndroidTest --stacktrace

      - store_artifacts:
          path: app/build/outputs/apk
          destination: apk_output

      - store_artifacts:
          path: app/screenshot.png
          destination: apk_output

#      - run:
#          name: Build Debug apk
#          command: ./gradlew clean assembleDebug
#      # upload apk to github
#      - deploy:
#          command: ./apkrelease.sh
#      pick artifact from
#      optional extra path
#          destination: buildApk
#      - store_avd_25_arm_results:
#          path: app/build/avd_25_arm-results